#!/bin/bash

source ./utils/utils.sh

LogStarted "=====================================> Provisioning infra via terraform.."

cd tf
terraform apply -auto-approve
cd ..

Log "sleeping to wait for instances to initialise.."
sleep 10
LogElapsedDuration

Log "===========================> Cleaning up from previous run.."
bash 00-clean-local-dir

Log "===========================> Installing RKE2 cluster.."
time bash 01-install-rke2.sh
LogElapsedDuration

Log "===========================> Installing longhorn.."
time bash 02-install-longhorn.sh
LogElapsedDuration

#Log "===========================> Installing kafka.."
#time bash 03-install-kafka.sh
#LogElapsedDuration

Log "===========================> Installing milvus.."
time bash 03-install-milvus.sh
#time bash 03-milvus-oss.sh
LogElapsedDuration

# --------------------------------------
LogElapsedDuration
LogCompleted "Done."

# tidy up
exit 0
